"""
Multi-Agent Implementation Module

This module defines the specific LangChain agents and their corresponding graph nodes
used in the multi-agent Retrieval-Augmented Generation (RAG) pipeline. It orchestrates 
the process of planning, retrieval, summarization, and verification.
"""
from __future__ import annotations

import re

from typing import Any, Dict, List

from langchain.agents import create_agent
from langchain_core.messages import AIMessage, HumanMessage, ToolMessage

from ..llm.factory import create_chat_model
from .prompts import (
    RETRIEVAL_SYSTEM_PROMPT,
    SUMMARIZATION_SYSTEM_PROMPT,
    VERIFICATION_SYSTEM_PROMPT,
    PLANNING_SYSTEM_PROMPT
)
from .state import QAState
from .tools import retrieval_tool


def _extract_last_ai_content(messages: List[object]) -> str:
    """
    Helper function to safely extract the most recent AI-generated text from a message history.

    Args:
        messages (List[object]): A list of LangChain message objects (HumanMessage, AIMessage, etc.).

    Returns:
        str: The content of the last AIMessage, or an empty string if none exists.
    """
    # Iterate backwards through the conversation history
    for msg in reversed(messages):
        if isinstance(msg, AIMessage):
            return str(msg.content)
    return ""

# ==============================================================================
# Agent Initialization
# ==============================================================================
# Initialize the specialized agents using the factory pattern to abstract away model specific details (e.g., OpenAI vs Local).
# Only the retrieval agent requires access to external tools (the vector store).

retrieval_agent = create_agent(
    model=create_chat_model(),
    tools=[retrieval_tool],
    system_prompt=RETRIEVAL_SYSTEM_PROMPT,
)

summarization_agent = create_agent(
    model=create_chat_model(),
    tools=[],
    system_prompt=SUMMARIZATION_SYSTEM_PROMPT,
)

verification_agent = create_agent(
    model=create_chat_model(),
    tools=[],
    system_prompt=VERIFICATION_SYSTEM_PROMPT,
)

planning_agent = create_agent(
    model=create_chat_model(),
    tools=[], 
    system_prompt=PLANNING_SYSTEM_PROMPT,
)

# ==============================================================================
# Graph Nodes
# ==============================================================================

def planning_node(state: QAState) -> QAState:
    """
    Executes the query planning and decomposition phase.

    This node intercepts the raw user question and asks the Planning Agent to evaluate it.
    Complex questions are broken down into a strategic plan and a list of specific sub-queries.

    Args:
        state (QAState): The current state of the graph containing the user's question.

    Returns:
        QAState: Updated state including the generated 'plan' (str) and 'sub_questions' (List[str]).
    """
    question = state["question"]
    
    # Invoke the planning agent with the user's initial question
    result = planning_agent.invoke({"messages": [HumanMessage(content=question)]})
    raw_output = _extract_last_ai_content(result.get("messages", []))
    
    # Parse the standardized output format defined in PLANNING_SYSTEM_PROMPT
    # Example expected format:
    # PLAN: I need to find X and compare it to Y.
    # QUESTIONS:
    # - What is X?
    # - What is Y?
    plan_match = re.search(r"PLAN:(.*?)QUESTIONS:", raw_output, re.DOTALL | re.IGNORECASE)
    questions_match = re.findall(r"-\s*(.*)", raw_output)
    
    # Fallback mechanisms in case the LLM deviates from the requested format
    plan = plan_match.group(1).strip() if plan_match else "General search"
    sub_questions = questions_match if questions_match else [question]

    return {**state, "plan": plan, "sub_questions": sub_questions}


def retrieval_node(state: QAState) -> QAState:
    """
    Executes iterative retrieval against the vector database based on the planned queries.

    This node takes the sub-questions generated by the planning_node and performs 
    a separate vector search for each one, merging all resulting context and citations 
    into a unified dataset for the summarizer.

    Args:
        state (QAState): Current state containing 'sub_questions' (or the original 'question').

    Returns:
        QAState: Updated state with concatenated 'context' (str) and aggregated 'citations' (Dict).
    """
    # Use generated sub_questions, or default to the raw question if planning failed/was skipped
    queries = state.get("sub_questions") or [state["question"]]
    
    all_context = []
    combined_citations = {}

    # Iterate through each sub-query to build comprehensive context
    for query in queries:
        result = retrieval_agent.invoke({"messages": [HumanMessage(content=query)]})
        messages = result.get("messages", []) or []
        
        # Isolate the messages returned by the retrieval_tool
        tool_msgs = [m for m in messages if isinstance(m, ToolMessage)]

        if tool_msgs:
            last_tool = tool_msgs[-1]
            # Append the retrieved chunk text to the master context list
            all_context.append(str(last_tool.content))
            
            # Merge the metadata/citation map from this query into the master map
            artifact = last_tool.artifact
            if isinstance(artifact, dict):
                combined_citations.update(artifact)

    # Join all context blocks with double newlines for clear separation in the prompt
    return {
        **state, 
        "context": "\n\n".join(all_context), 
        "citations": combined_citations
    }


def summarization_node(state: QAState) -> QAState:
    """
    Drafts an initial answer based strictly on the retrieved context.

    Args:
        state (QAState): Current state containing the user 'question' and retrieved 'context'.

    Returns:
        QAState: Updated state with the generated 'draft_answer' (str).
    """
    question = state["question"]
    context = state.get("context") or ""

    # Construct the prompt payload combining the user intent and the RAG data
    user_content = (
        f"Question:\n{question}\n\n"
        f"CONTEXT:\n{context}\n"
    )

    result = summarization_agent.invoke({"messages": [HumanMessage(content=user_content)]})
    draft_answer = _extract_last_ai_content(result.get("messages", []) or [])

    return {**state, "draft_answer": draft_answer}


def verification_node(state: QAState) -> QAState:
    """
    Audits the drafted answer for accuracy and correct citation formatting.

    This node acts as a hallucination filter. It reviews the draft against the original 
    context to ensure all claims are supported and appropriately tagged with citation IDs.

    Args:
        state (QAState): Current state with 'question', 'context', and 'draft_answer'.

    Returns:
        QAState: Updated state with the final, verified 'answer' (str).
    """
    question = state["question"]
    context = state.get("context") or ""
    draft_answer = state.get("draft_answer") or ""

    # Provide the Verification Agent with all necessary data points to perform the audit
    user_content = f"""
Question:
{question}

CONTEXT:
{context}

Draft Answer:
{draft_answer}
""".strip()

    result = verification_agent.invoke({"messages": [HumanMessage(content=user_content)]})
    answer = _extract_last_ai_content(result.get("messages", []) or [])

    return {**state, "answer": answer}
