"""
LangGraph State Schema Module

This module defines the shared state schema (QAState) for the multi-agent RAG pipeline.
In LangGraph architecture, state acts as the central memory object passed between every 
node in the DAG (Directed Acyclic Graph). Every specialized agent (node) reads from 
and writes to this state, enabling complex, multi-step data orchestration.
"""

from __future__ import annotations
from typing import Dict, List, NotRequired, TypedDict


class QAState(TypedDict):
    """
    Type definition for the pipeline's operational state.
    
    Using a TypedDict ensures type safety and enforces strict data contracts between 
    the different nodes (Planning, Retrieval, Summarization, Verification) in the graph.
    Keys marked as NotRequired indicate optional lifecycle properties.
    """
    
    # --------------------------------------------------------------------------
    # 1. Input State
    # --------------------------------------------------------------------------
    
    # The original query submitted by the user. 
    # Populated at START; acts as the primary driver for the graph execution.
    question: str
    
    # Optional metadata filter for the vector store.
    # If set via the API payload, retrieval operations should be strictly limited 
    # to chunks belonging to this specific PDF/document source.
    document_scope: NotRequired[str | None]

    # --------------------------------------------------------------------------
    # 2. Planning State
    # --------------------------------------------------------------------------
    
    # A high-level textual description of the LLM's search strategy.
    # Populated by the 'planning_node'.
    plan: NotRequired[str | None]
    
    # The decomposed, specific queries generated from the main question.
    # Consumed by the 'retrieval_node' to execute iterative vector searches.
    sub_questions: NotRequired[List[str]]

    # --------------------------------------------------------------------------
    # 3. Retrieval State
    # --------------------------------------------------------------------------
    
    # The aggregated raw text chunks retrieved from the vector database.
    # Serves as the strict "ground truth" boundary for the summarization_node.
    context: str | None
    
    # A dictionary mapping citation IDs (e.g., 'chunk-abc') to their full metadata 
    # (source filename, page number, raw snippet). 
    # Essential for UI mapping and the backend's deterministic confidence calculation.
    citations: Dict[str, dict] | None

    # --------------------------------------------------------------------------
    # 4. Generation & Verification State
    # --------------------------------------------------------------------------
    
    # The initial response generated by the summarization_node.
    # This is an intermediate state (unverified) and is never exposed to the client.
    draft_answer: str | None
    
    # The final, verified response after passing through the verification_node.
    # Hallucinations and invalid citations are stripped out before this is finalized.
    answer: str | None
    
    # A deterministically computed score ("high", "medium", "low").
    # Calculated mathematically in the graph.py orchestrator based on the number 
    # of unique, verified vector chunks cross-referenced in the final answer.
    confidence: NotRequired[str]