"""
QA Service Layer Module

This module implements the Service Layer design pattern for the Question-Answering pipeline.
It acts as a stable, decoupled interface between the HTTP API controllers (FastAPI routes) 
and the complex, stateful LangGraph orchestration logic.

By enforcing this boundary, the API layer doesn't need to understand LangGraph's 
internal state management, checkpointers, or node execution flow. It simply calls 
a service function and receives a formatted dictionary in return.
"""

from typing import Dict, Any
from ..core.agents.graph import run_qa_flow


def answer_question(question: str, thread_id: str, document_scope: str | None = None) -> Dict[str, Any]:
    """
    Executes the multi-agent QA flow and retrieves a verified answer.

    This function serves as the primary entry point for the frontend's chat interface.
    It passes the user's input down to the LangGraph orchestrator while maintaining 
    the necessary context (thread ID) for conversational memory.

    Senior Note on Threading:
    The `thread_id` is critical. It allows the underlying LangGraph Checkpointer 
    (MemorySaver/Postgres) to load the exact historical context of this specific user's 
    conversation before the Planning Agent begins reasoning.

    Args:
        question (str): The raw, natural language question submitted by the user.
        thread_id (str): A unique session identifier (e.g., a UUID) generated by the 
            frontend to isolate and persist this specific conversation's memory.
        document_scope (str | None): Optional filename (e.g., "report.pdf"). If provided, 
            it strictly bounds the vector database retrieval to only that document, 
            preventing cross-contamination of answers from other uploaded files.

    Returns:
        Dict[str, Any]: A comprehensive payload containing:
            - "answer": The final, verified string response.
            - "context": The raw chunks retrieved from Pinecone.
            - "plan": The decomposed strategy used by the agents.
            - "sub_questions": The actual queries executed against the vector store.
            - "citations": A dictionary mapping chunk IDs to their metadata.
            - "confidence": A deterministic string ("high", "medium", "low").
    """
    # Delegate the complex DAG execution to the graph module
    return run_qa_flow(question, thread_id=thread_id, document_scope=document_scope)