"""
Data Models Module

This module defines the Pydantic schemas used for request validation and response 
serialization. By leveraging Pydantic's BaseModel, we ensure that all data entering 
and leaving the API adheres to a strict contract, providing automatic documentation 
via OpenAPI (Swagger) and robust type safety for the frontend.
"""

from typing import Dict, Any, Optional, List
from pydantic import BaseModel, Field

class QuestionRequest(BaseModel):
    """
    Schema for incoming QA requests.
    
    Includes support for conversational memory via thread IDs and contextual 
    filtering via document scopes.
    """
    # The primary natural language query from the user.
    question: str = Field(..., description="The user's question.")
    
    # Unique identifier used by the LangGraph checkpointer to retrieve 
    # previous conversation state for this specific user session.
    thread_id: Optional[str] = Field(None, description="Unique session ID for memory.")
    
    # Metadata filter to restrict vector search to a specific file (e.g., 'invoice.pdf').
    # Essential for the "Selected PDF" search mode in the UI.
    document_scope: Optional[str] = Field(
        None, description="Optional specific PDF filename to query."
    )

class QAResponse(BaseModel):
    """
    Schema for standardized API responses.
    
    This model encapsulates the full output of the multi-agent reasoning process, 
    including transparency data (the plan) and evidence (citations).
    """
    # The final, verified answer string generated by the agents.
    answer: str
    
    # The raw text blocks retrieved from the vector store for auditability.
    context: str
    
    # The high-level strategy generated by the Planning Agent.
    plan: Optional[str] = None
    
    # The specific sub-queries derived from the original question.
    sub_questions: Optional[List[str]] = None
    
    # A mapping of citation IDs to their respective source metadata and snippets.
    citations: Optional[Dict[str, Any]] = None
    
    # Deterministic evidence-based score: "high", "medium", or "low".
    confidence: str = "low"
    
    # Echoes the session ID back to the client to confirm state persistence.
    thread_id: Optional[str] = None
    